"""Add tax_rate to producto

Revision ID: 08181e47fe1e
Revises: fde620f42cae
Create Date: 2025-05-25 20:45:48.877690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08181e47fe1e'
down_revision = 'fde620f42cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
