"""Agregar tabla facturacion

Revision ID: 08e73f759155
Revises: d17a8d95e07b
Create Date: 2024-08-18 09:34:46.861201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e73f759155'
down_revision = 'd17a8d95e07b'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('lote', sa.String(length=50), nullable=False),
    sa.Column('fecha_fabricacion', sa.String(length=10), nullable=False),
    sa.Column('fecha_expiracion', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facturacion')
    # ### end Alembic commands ###
