"""Agregados campos flete_local y costo_total_almacen a Importacion

Revision ID: 0b6efb8b82e5
Revises: c5875ab83b73
Create Date: 2024-09-28 15:54:05.990151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6efb8b82e5'
down_revision = 'c5875ab83b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('importacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flete_local', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('costo_total_almacen', sa.Float(), nullable=True))
        batch_op.alter_column('cif_ang',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('importacion', schema=None) as batch_op:
        batch_op.alter_column('cif_ang',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_column('costo_total_almacen')
        batch_op.drop_column('flete_local')

    # ### end Alembic commands ###
