"""Migración inicial: creación de tablas

Revision ID: 55278b70cebe
Revises: 
Create Date: 2025-02-15 12:47:38.390307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55278b70cebe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('temperatura', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('lote', sa.String(length=50), nullable=False),
    sa.Column('fecha_fabricacion', sa.String(length=10), nullable=False),
    sa.Column('fecha_expiracion', sa.String(length=10), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=100), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_cajas', sa.Integer(), nullable=False),
    sa.Column('cantidad_total', sa.Float(), nullable=False),
    sa.Column('precio_fob_unidad', sa.Float(), nullable=False),
    sa.Column('flete', sa.Float(), nullable=False),
    sa.Column('arancel', sa.Float(), nullable=False),
    sa.Column('costo_aduana', sa.Float(), nullable=False),
    sa.Column('precio_jomar', sa.Float(), nullable=False),
    sa.Column('precio_retail', sa.Float(), nullable=False),
    sa.Column('cif_ang', sa.Float(), nullable=True),
    sa.Column('ob_ang', sa.Float(), nullable=True),
    sa.Column('fecha_importacion', sa.DateTime(), nullable=True),
    sa.Column('flete_local', sa.Float(), nullable=True),
    sa.Column('costo_total_almacen', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recepcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('proveedor', sa.String(length=100), nullable=False),
    sa.Column('numero_factura', sa.String(length=100), nullable=False),
    sa.Column('recibido_en', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recepcion')
    op.drop_table('importacion')
    op.drop_table('facturacion')
    op.drop_table('producto')
    op.drop_table('cliente')
    # ### end Alembic commands ###
