"""Agregar modelo de Cliente y referencia en Facturación

Revision ID: 710eed39ac50
Revises: a88524f03707
Create Date: 2024-08-22 00:13:47.448561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710eed39ac50'
down_revision = 'a88524f03707'
branch_labels = None
depends_on = None


def upgrade():
    # Verificar si la tabla ya existe antes de crearla
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'cliente' not in inspector.get_table_names():
        op.create_table('cliente',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('nombre', sa.String(length=100), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_facturacion_cliente', 'cliente', ['cliente_id'], ['id'])
        batch_op.drop_column('cliente')





def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente', sa.String(length=100), nullable=False))
        batch_op.drop_constraint('fk_facturacion_cliente', type_='foreignkey')
        batch_op.drop_column('cliente_id')

    op.drop_table('cliente')
    # ### end Alembic commands ###

