"""empty message

Revision ID: 877fd3b2a867
Revises: 710eed39ac50
Create Date: 2024-08-22 00:34:42.104047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877fd3b2a867'
down_revision = '710eed39ac50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_foreign_key('fk_facturacion_cliente', 'cliente', ['cliente_id'], ['id'])
        batch_op.drop_column('cliente')



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###
