"""Agregar columna cif_ang

Revision ID: 8a24ec75021e
Revises: 9ec7baf024a4
Create Date: 2024-09-28 14:48:36.497833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a24ec75021e'
down_revision = '9ec7baf024a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('importacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cif_ang', sa.Float(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('importacion', schema=None) as batch_op:
        batch_op.drop_column('cif_ang')

    # ### end Alembic commands ###
