"""Permitir valores NULL en lote, fecha_fabricacion y fecha_expiracion

Revision ID: 9b5b69d7a839
Revises: d8bda71c9188
Create Date: 2025-05-15 00:57:20.548971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5b69d7a839'
down_revision = 'd8bda71c9188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalle_pedido', 'lote',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('detalle_pedido', 'fecha_fabricacion',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('detalle_pedido', 'fecha_expiracion',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalle_pedido', 'fecha_expiracion',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('detalle_pedido', 'fecha_fabricacion',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('detalle_pedido', 'lote',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
