"""add territorio_id to cliente

Revision ID: 9d79cf425a74
Revises: 4cf82d9de5ac
Create Date: 2025-05-31 12:41:08.202981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d79cf425a74'
down_revision = '4cf82d9de5ac'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    dialect = bind.dialect.name if bind is not None else None

    if dialect == 'sqlite':
        inspector = sa.inspect(bind)
        cols = {c['name'] for c in inspector.get_columns('cliente')}
        if 'territorio_id' not in cols:
            op.add_column('cliente', sa.Column('territorio_id', sa.Integer(), nullable=True))
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('territorio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cliente', 'territorio', ['territorio_id'], ['id'])
    op.drop_constraint('fk_facturacion_creado_por', 'facturacion', type_='foreignkey')
    op.drop_constraint('fk_facturacion_vendedor', 'facturacion', type_='foreignkey')
    op.drop_column('facturacion', 'creado_por')
    op.drop_column('facturacion', 'vendedor_id')
    op.drop_constraint('fk_pedido_modificado_por', 'pedido', type_='foreignkey')
    op.drop_constraint('fk_pedido_vendedor', 'pedido', type_='foreignkey')
    op.drop_constraint('fk_pedido_creado_por', 'pedido', type_='foreignkey')
    op.drop_column('pedido', 'modificado_por')
    op.drop_column('pedido', 'creado_por')
    op.drop_column('pedido', 'fecha_modificacion')
    op.drop_column('pedido', 'vendedor_id')
    op.drop_constraint('fk_recepcion_creado_por', 'recepcion', type_='foreignkey')
    op.drop_column('recepcion', 'creado_por')
    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    dialect = bind.dialect.name if bind is not None else None

    if dialect == 'sqlite':
        inspector = sa.inspect(bind)
        cols = {c['name'] for c in inspector.get_columns('cliente')}
        if 'territorio_id' in cols:
            op.drop_column('cliente', 'territorio_id')
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recepcion', sa.Column('creado_por', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_recepcion_creado_por', 'recepcion', 'vendedor', ['creado_por'], ['id'])
    op.add_column('pedido', sa.Column('vendedor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pedido', sa.Column('fecha_modificacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('pedido', sa.Column('creado_por', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pedido', sa.Column('modificado_por', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_pedido_creado_por', 'pedido', 'vendedor', ['creado_por'], ['id'])
    op.create_foreign_key('fk_pedido_vendedor', 'pedido', 'vendedor', ['vendedor_id'], ['id'])
    op.create_foreign_key('fk_pedido_modificado_por', 'pedido', 'vendedor', ['modificado_por'], ['id'])
    op.add_column('facturacion', sa.Column('vendedor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('facturacion', sa.Column('creado_por', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_facturacion_vendedor', 'facturacion', 'vendedor', ['vendedor_id'], ['id'])
    op.create_foreign_key('fk_facturacion_creado_por', 'facturacion', 'vendedor', ['creado_por'], ['id'])
    op.drop_constraint(None, 'cliente', type_='foreignkey')
    op.drop_column('cliente', 'territorio_id')
    # ### end Alembic commands ###
