"""Crear tabla de importaciones

Revision ID: 9ec7baf024a4
Revises: 877fd3b2a867
Create Date: 2024-09-27 21:31:00.403827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec7baf024a4'
down_revision = '877fd3b2a867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('importacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=100), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_cajas', sa.Integer(), nullable=False),
    sa.Column('cantidad_total', sa.Float(), nullable=False),
    sa.Column('precio_fob_unidad', sa.Float(), nullable=False),
    sa.Column('flete', sa.Float(), nullable=False),
    sa.Column('arancel', sa.Float(), nullable=False),
    sa.Column('costo_aduana', sa.Float(), nullable=False),
    sa.Column('precio_jomar', sa.Float(), nullable=False),
    sa.Column('precio_retail', sa.Float(), nullable=False),
    sa.Column('fecha_importacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.alter_column('fecha_registro',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('recepcion', schema=None) as batch_op:
        batch_op.alter_column('numero_factura',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('recibido_en',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recepcion', schema=None) as batch_op:
        batch_op.alter_column('recibido_en',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('numero_factura',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.alter_column('fecha_registro',
               existing_type=sa.DATETIME(),
               nullable=False)

    op.drop_table('importacion')
    # ### end Alembic commands ###
