"""Agregar columna fecha_registro a la tabla facturacion

Revision ID: a8242fa1a2bf
Revises: 08e73f759155
Create Date: 2024-08-18 10:15:20.679361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8242fa1a2bf'
down_revision = '08e73f759155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###
