"""Agregar columna ob_ang

Revision ID: c5875ab83b73
Revises: 8a24ec75021e
Create Date: 2024-09-28 14:53:20.560930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5875ab83b73'
down_revision = '8a24ec75021e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('importacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ob_ang', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('importacion', schema=None) as batch_op:
        batch_op.drop_column('ob_ang')

    # ### end Alembic commands ###
