"""Corregir modelo Facturacion: mantener fechas como String y añadir relativedelta

Revision ID: ca413cb75f80
Revises: 97ef1728c404
Create Date: 2024-09-28 21:44:49.359610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca413cb75f80'
down_revision = 'd17a8d95e07b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.alter_column('fecha_fabricacion',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('fecha_expiracion',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.alter_column('fecha_expiracion',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('fecha_fabricacion',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
