"""Eliminar lote de Recepcion

Revision ID: d17a8d95e07b
Revises: 
Create Date: 2024-08-16 19:39:41.138058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17a8d95e07b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recepcion', schema=None) as batch_op:
        batch_op.drop_column('lote')
        batch_op.drop_column('fecha_fabricacion')
        batch_op.drop_column('fecha_expiracion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recepcion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_expiracion', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('fecha_fabricacion', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('lote', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
