"""Add cajas to detalle_pedido

Revision ID: d8bda71c9188
Revises: 833a686387a1
Create Date: 2025-05-15 00:15:43.675634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bda71c9188'
down_revision = '833a686387a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalle_pedido', sa.Column('cajas', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detalle_pedido', 'cajas')
    # ### end Alembic commands ###
