"""Inicialización después de corrección

Revision ID: e8897a04e926
Revises: 724947d7525c
Create Date: 2024-08-18 10:44:05.225170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8897a04e926'
down_revision = '724947d7525c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_facturacion')
    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.alter_column('fecha_registro',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.alter_column('fecha_registro',
               existing_type=sa.DATETIME(),
               nullable=True)

    op.create_table('_alembic_tmp_facturacion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('producto_id', sa.INTEGER(), nullable=False),
    sa.Column('peso', sa.FLOAT(), nullable=False),
    sa.Column('cliente', sa.VARCHAR(length=100), nullable=False),
    sa.Column('lote', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fecha_fabricacion', sa.VARCHAR(length=10), nullable=False),
    sa.Column('fecha_expiracion', sa.VARCHAR(length=10), nullable=False),
    sa.Column('fecha_registro', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
