"""add qbo_id to cliente and producto

Revision ID: fde620f42cae
Revises: ed70f8d30408
Create Date: 2025-05-25 15:01:58.422402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde620f42cae'
down_revision = 'ed70f8d30408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('qbo_id', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'cliente', ['qbo_id'])
    op.add_column('producto', sa.Column('qbo_id', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'producto', ['qbo_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'producto', type_='unique')
    op.drop_column('producto', 'qbo_id')
    op.drop_constraint(None, 'cliente', type_='unique')
    op.drop_column('cliente', 'qbo_id')
    # ### end Alembic commands ###
